-- Add new checklist fields to viviendas table
ALTER TABLE viviendas 
ADD COLUMN IF NOT EXISTS bomba_agua BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS soldadura BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS artefactado BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS pruebas_electricas BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS rotulado BOOLEAN DEFAULT FALSE;
